let portfolioThemeMode='auto';
let portfolioVisualStyle='classic';
try{portfolioThemeMode=localStorage.getItem('portfolio-theme')||'auto';portfolioVisualStyle=localStorage.getItem('portfolio-visual-style')||'classic'}catch(e){}
function loadCss(href){if(document.querySelector('link[href^="'+href.split('?')[0]+'"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link)}
function loadJs(src){if(document.querySelector('script[src^="'+src.split('?')[0]+'"]'))return;const script=document.createElement('script');script.async=false;script.src=src;document.body.appendChild(script)}
function portfolioAutoTheme(){const h=new Date().getHours();return h>=7&&h<20?'light':'dark'}
function portfolioApplyTheme(){const t=portfolioThemeMode==='auto'?portfolioAutoTheme():portfolioThemeMode;document.body.setAttribute('data-theme',t);document.body.setAttribute('data-visual-style',portfolioVisualStyle);const b=document.getElementById('themeButton');if(b)b.textContent=portfolioThemeMode==='auto'?'Auto':portfolioThemeMode==='light'?'Claro':'Oscuro'}
function portfolioThemePanel(){let panel=document.getElementById('themePanel');if(panel)return panel;panel=document.createElement('div');panel.id='themePanel';panel.className='theme-panel';panel.innerHTML='<button type="button" data-style="classic">Clásico<small>Estilo cristal actual</small></button><button type="button" data-style="aurora">Aurora<small>Cristal reforzado y acento técnico</small></button><button type="button" data-style="nebula">Nebula<small>Azul espacial con brillo frío</small></button><button type="button" data-style="solstice">Solstice<small>Ámbar cálido y verde suave</small></button>';document.body.appendChild(panel);panel.addEventListener('click',event=>{const btn=event.target.closest('button[data-style]');if(!btn)return;portfolioVisualStyle=btn.dataset.style;try{localStorage.setItem('portfolio-visual-style',portfolioVisualStyle)}catch(e){}portfolioApplyTheme();portfolioMarkPanel();panel.classList.remove('open')});return panel}
function portfolioMarkPanel(){const panel=document.getElementById('themePanel');if(!panel)return;panel.querySelectorAll('button[data-style]').forEach(btn=>btn.classList.toggle('active',btn.dataset.style===portfolioVisualStyle))}
function portfolioToggleThemePanel(){const panel=portfolioThemePanel();portfolioMarkPanel();panel.classList.toggle('open')}
function normalizeHeroName(){const last=document.querySelector('.hero-copy h1 span:last-child');if(last)last.textContent='Pico Perez'}
function appendProject(grid,project){if(!grid||grid.querySelector('[data-project-id="'+project.id+'"]'))return;const card=document.createElement('article');card.className='project-card featured';card.dataset.projectId=project.id;card.dataset.url=project.url;card.innerHTML='<div class="project-head"><img class="project-icon" src="'+project.icon+'" alt=""><h3>'+project.title+'</h3></div><p data-project-key="'+project.key+'">'+project.description+'</p><div class="project-foot"><a class="repo-link" href="'+project.repo+'" target="_blank" rel="noreferrer" aria-label="Repositorio de '+project.title+'"></a><div class="tag-list"><span>'+project.tags[0]+'</span><span>'+project.tags[1]+'</span></div></div>';grid.appendChild(card)}
function ensureProjectCatalog(){const cards=[...document.querySelectorAll('.project-card')];const cams=cards.find(card=>card.querySelector('h3')?.textContent.trim().toLowerCase()==='cams');if(cams){const icon=cams.querySelector('.project-icon');if(icon)icon.src='https://alejandropico.github.io/Cams/icons/favicon.svg?v=20260712';const description=cams.querySelector(':scope>p');if(description){description.dataset.projectKey='cams';description.textContent='Visor mundial de webcams públicas, emisiones en directo y capturas organizadas en una interfaz rápida, visual y centralizada.'}}const grid=document.querySelector('#proyectos .project-grid');[
{id:'evolucion-estelar',key:'evolucionEstelar',title:'Evolución Estelar',url:'https://alejandropico.github.io/EvolucionEstelar/',repo:'https://github.com/AlejandroPico/EvolucionEstelar',icon:'https://alejandropico.github.io/EvolucionEstelar/favicon.svg',description:'Experiencia narrativa 3D para descubrir cómo nacen, evolucionan y mueren las estrellas mediante decisiones, rutas físicas y destinos como supernovas, púlsares o agujeros negros.',tags:['Astronomía','Educación 3D']},
{id:'modelo-estandar',key:'modeloEstandar',title:'Modelo Estándar',url:'https://alejandropico.github.io/ModeloEstandar/',repo:'https://github.com/AlejandroPico/ModeloEstandar',icon:'https://alejandropico.github.io/ModeloEstandar/favicon.svg',description:'Atlas científico interactivo para explorar partículas elementales, fuerzas fundamentales, antimateria y la estructura del Modelo Estándar desde el átomo hasta quarks, gluones y leptones.',tags:['Física de partículas','Ciencia']},
{id:'media-world',key:'mediaWorld',title:'Media World',url:'https://alejandropico.github.io/MediaWorld/',repo:'https://github.com/AlejandroPico/MediaWorld',icon:'https://alejandropico.github.io/MediaWorld/mediaworld-favicon.svg',description:'Explorador mundial de radio y televisión sobre un globo 3D, con medios geolocalizados, búsqueda, filtros y reproducción manual de emisiones verificadas.',tags:['Radio y TV','Globo 3D']},
{id:'atlas-editor',key:'atlasEditor',title:'Atlas Editor',url:'https://alejandropico.github.io/Editor/',repo:'https://github.com/AlejandroPico/Editor',icon:'https://alejandropico.github.io/Editor/favicon.svg',description:'Editor vectorial y portable para crear esquemas, mapas, cronologías, infografías y redes interactivas, con lienzo SVG, ejes jerárquicos, SQLite interno y exportación a visores web.',tags:['Editor vectorial','SVG']},
{id:'mindsage',key:'mindSage',title:'MindSage',url:'https://alejandropico.github.io/Biografias/',repo:'https://github.com/AlejandroPico/Biografias',icon:'https://alejandropico.github.io/Biografias/favicon.svg',description:'Archivo vivo intergeneracional para conservar historias, voces, recuerdos y relaciones familiares mediante biografías, entrevistas, cronologías, atlas, árbol genealógico y biblioteca multimedia.',tags:['Memoria','Biografías']},
{id:'arteteca',key:'arteteca',title:'Arteteca',url:'https://alejandropico.github.io/Arteteca/',repo:'https://github.com/AlejandroPico/Arteteca',icon:'https://alejandropico.github.io/Arteteca/favicon.svg',description:'Exposición digital abierta que reúne obras de distintas épocas y disciplinas en un mosaico cambiante, con búsqueda, filtros, fichas editoriales y visor inmersivo.',tags:['Arte','Exposición']}
].forEach(project=>appendProject(grid,project))}
function prepareProjectSlots(){document.querySelectorAll('#proyectos .project-grid>.project-card').forEach(card=>{if(card.parentElement?.classList.contains('project-slot'))return;const slot=document.createElement('div');slot.className='project-slot';card.before(slot);slot.appendChild(card)})}
function bindMenu(){const menuButton=document.querySelector('.menu-button');const navLinks=document.querySelector('.nav-links');if(menuButton&&navLinks){menuButton.addEventListener('click',()=>{const isOpen=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(isOpen))});navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}))}}
function bindTheme(){const b=document.getElementById('themeButton');portfolioApplyTheme();if(b)b.addEventListener('click',event=>{if(event.altKey){event.preventDefault();portfolioToggleThemePanel();return}portfolioThemeMode=portfolioThemeMode==='auto'?'light':portfolioThemeMode==='light'?'dark':'auto';try{localStorage.setItem('portfolio-theme',portfolioThemeMode)}catch(e){}portfolioApplyTheme()});document.addEventListener('click',event=>{const panel=document.getElementById('themePanel');if(panel&&panel.classList.contains('open')&&!panel.contains(event.target)&&event.target!==b)panel.classList.remove('open')});const l=document.getElementById('languageSelect');if(l)l.addEventListener('change',()=>{document.documentElement.lang=l.value;try{localStorage.setItem('portfolio-language',l.value)}catch(e){}});setInterval(()=>{if(portfolioThemeMode==='auto')portfolioApplyTheme()},60000)}
function bindProjectCards(){document.querySelectorAll('.project-card[data-url]').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='true';card.setAttribute('tabindex','0');card.addEventListener('click',event=>{if(event.target.closest('a'))return;window.open(card.dataset.url,'_blank','noopener')});card.addEventListener('keydown',event=>{if(event.key==='Enter')window.open(card.dataset.url,'_blank','noopener')})})}
function initProgressNavigation(){const nav=document.querySelector('.site-nav');const links=[...document.querySelectorAll('.nav-links a[href^="#"]')].filter(link=>document.querySelector(link.getAttribute('href')));if(!nav||!links.length)return;if(!document.getElementById('progress-nav-style')){const style=document.createElement('style');style.id='progress-nav-style';style.textContent='.site-nav{overflow:visible}.scroll-progress{position:absolute;left:0;top:0;width:100%;height:3px;pointer-events:none;background:color-mix(in srgb,var(--line) 65%,transparent);z-index:50}.scroll-progress span{display:block;width:0;height:100%;background:linear-gradient(90deg,color-mix(in srgb,var(--accent) 45%,var(--muted)),color-mix(in srgb,var(--accent-2) 50%,var(--accent)));opacity:.82;transition:width .08s linear;box-shadow:0 0 14px color-mix(in srgb,var(--accent) 24%,transparent)}.nav-links a[href^="#"].active{color:var(--text);background:color-mix(in srgb,var(--surface) 56%,transparent);border-color:color-mix(in srgb,var(--accent) 36%,var(--line))}.nav-links a[href^="#"].active::after{display:none!important;content:none!important}';document.head.appendChild(style)}let progress=document.querySelector('.scroll-progress');if(!progress){progress=document.createElement('div');progress.className='scroll-progress';progress.innerHTML='<span></span>';nav.appendChild(progress)}const bar=progress.querySelector('span');const sections=links.map(link=>({link,section:document.querySelector(link.getAttribute('href'))}));function updateProgress(){const doc=document.documentElement;const max=Math.max(1,doc.scrollHeight-window.innerHeight);const value=Math.min(1,Math.max(0,window.scrollY/max));bar.style.width=(value*100).toFixed(2)+'%';const checkpoint=window.scrollY+(window.innerHeight*.40);let current=sections[0];sections.forEach(item=>{if(item.section.offsetTop<=checkpoint)current=item});links.forEach(link=>link.classList.remove('active'));if(current)current.link.classList.add('active')}updateProgress();window.addEventListener('scroll',updateProgress,{passive:true});window.addEventListener('resize',updateProgress)}
function initScrollReveal(){const items=[...document.querySelectorAll('.project-slot,.tech-card,.resume-column,.value-grid p,.profile-text p,.contact-form')];if(!items.length)return;if(!document.getElementById('scroll-reveal-style')){const style=document.createElement('style');style.id='scroll-reveal-style';style.textContent='@media (prefers-reduced-motion:no-preference){.reveal-item{opacity:0;transform:translateY(18px);transition:opacity .58s ease,transform .58s ease;transition-delay:var(--reveal-delay,0ms)}.reveal-item.is-visible{opacity:1;transform:none}}';document.head.appendChild(style)}items.forEach((item,index)=>{item.classList.add('reveal-item');item.style.setProperty('--reveal-delay',Math.min(index%8,6)*45+'ms')});if(!('IntersectionObserver'in window)){items.forEach(item=>item.classList.add('is-visible'));return}const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.14,rootMargin:'0px 0px -6% 0px'});items.forEach(item=>observer.observe(item))}
function initPortfolio(){const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();normalizeHeroName();ensureProjectCatalog();prepareProjectSlots();bindMenu();bindTheme();bindProjectCards();initProgressNavigation();setTimeout(initScrollReveal,450)}
loadCss('layout-polish.css?v=20260707-1');
loadCss('glass-ui.css?v=20260708-2');
loadCss('theme-variants.css?v=20260708-2');
loadCss('project-gallery.css?v=20260716-4');
portfolioApplyTheme();
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',initPortfolio,{once:true});else initPortfolio();
document.addEventListener('portfolio-language-change',()=>setTimeout(initScrollReveal,120));
loadJs('i18n/index.js?v=20260728-1');