const portfolioThemeLabels={
  es:{auto:'Automático',morning:'Mañana',afternoon:'Tarde',night:'Noche'},
  ca:{auto:'Automàtic',morning:'Matí',afternoon:'Tarda',night:'Nit'},
  en:{auto:'Automatic',morning:'Morning',afternoon:'Afternoon',night:'Night'},
  fr:{auto:'Automatique',morning:'Matin',afternoon:'Après-midi',night:'Nuit'},
  de:{auto:'Automatisch',morning:'Morgen',afternoon:'Nachmittag',night:'Nacht'},
  pt:{auto:'Automático',morning:'Manhã',afternoon:'Tarde',night:'Noite'},
  it:{auto:'Automatico',morning:'Mattina',afternoon:'Pomeriggio',night:'Notte'}
};
const solarPalettes={
  morning:{bg:'#f8f5ee',surface:'#fffdf8',surface2:'#eee8dd',text:'#222326',muted:'#686159',line:'rgba(49,43,36,.14)',accent:'#b65f31',accent2:'#356b7c',chip:'#f1e3cb',nav:'rgba(248,245,238,.90)'},
  afternoon:{bg:'#f2dfc5',surface:'#fff2df',surface2:'#e7cfae',text:'#2c2520',muted:'#735f4d',line:'rgba(78,55,36,.17)',accent:'#c46b35',accent2:'#8e664b',chip:'#ead0ad',nav:'rgba(242,223,197,.90)'},
  night:{bg:'#0f141b',surface:'#171f2a',surface2:'#202b38',text:'#f3efe7',muted:'#b8b1a6',line:'rgba(255,255,255,.14)',accent:'#d99a5d',accent2:'#7fb7c9',chip:'#2a3442',nav:'rgba(15,20,27,.88)'}
};
function clamp01(v){return Math.max(0,Math.min(1,v))}
function smoothstep(v){v=clamp01(v);return v*v*(3-2*v)}
function parseColor(value){const s=value.trim();if(s.startsWith('#')){let h=s.slice(1);if(h.length===3)h=h.split('').map(c=>c+c).join('');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),1]}const m=s.match(/rgba?\(([^)]+)\)/i);if(!m)return[0,0,0,1];const p=m[1].split(',').map(x=>parseFloat(x.trim()));return[p[0],p[1],p[2],p.length>3?p[3]:1]}
function mixColor(a,b,t){const x=parseColor(a),y=parseColor(b),k=smoothstep(t);const c=x.map((v,i)=>v+(y[i]-v)*k);return`rgba(${Math.round(c[0])},${Math.round(c[1])},${Math.round(c[2])},${Math.max(0,Math.min(1,c[3])).toFixed(3)})`}
function mixPalette(a,b,t){const out={};Object.keys(a).forEach(k=>out[k]=mixColor(a[k],b[k],t));return out}
function dayOfYear(date){const start=new Date(date.getFullYear(),0,0);return Math.floor((date-start)/86400000)}
function timezoneProfile(){let tz='';try{tz=Intl.DateTimeFormat().resolvedOptions().timeZone||''}catch(e){}const south=/(Australia|Pacific\/Auckland|Pacific\/Chatham|Africa\/(Johannesburg|Maputo|Windhoek)|America\/(Argentina|Santiago|Montevideo|Sao_Paulo|Asuncion)|Indian\/Reunion)/.test(tz);let amplitude=2.55;if(/(Reykjavik|Helsinki|Stockholm|Oslo|Tallinn|Riga|Vilnius|Anchorage)/.test(tz))amplitude=3.7;else if(/(Singapore|Jakarta|Kuala_Lumpur|Honolulu|Bangkok|Manila|Nairobi|Quito)/.test(tz))amplitude=.65;else if(/(Sydney|Melbourne|Auckland|Santiago|Buenos_Aires|Cape_Town|Johannesburg)/.test(tz))amplitude=2.7;else if(/(Europe|America\/New_York|America\/Chicago|America\/Denver|America\/Los_Angeles|Asia\/Tokyo|Asia\/Seoul)/.test(tz))amplitude=2.55;return{tz,hemisphere:south?-1:1,amplitude}}
function isDaylightSaving(date){const jan=new Date(date.getFullYear(),0,15);const jul=new Date(date.getFullYear(),6,15);const standard=Math.max(jan.getTimezoneOffset(),jul.getTimezoneOffset());return date.getTimezoneOffset()<standard}
function solarWindow(date){const profile=timezoneProfile();const doy=dayOfYear(date);const seasonal=Math.sin((2*Math.PI*(doy-80))/365.2422)*profile.hemisphere;const dayLength=Math.max(8,Math.min(16,12+profile.amplitude*seasonal));const dst=isDaylightSaving(date);let solarNoon=12.75+(dst?.45:0);if(profile.tz==='Europe/Madrid')solarNoon=12.95+(dst?.5:0);else if(profile.tz==='Europe/Lisbon')solarNoon=12.55+(dst?.45:0);else if(profile.tz.startsWith('America/'))solarNoon=12.65+(dst?.35:0);const sunrise=solarNoon-dayLength/2;const sunset=solarNoon+dayLength/2;return{sunrise,sunset,solarNoon,dayLength}}
function currentHour(date){return date.getHours()+date.getMinutes()/60+date.getSeconds()/3600}
function automaticSolarState(date=new Date()){const {sunrise,sunset,solarNoon}=solarWindow(date);const h=currentHour(date);const dawnStart=sunrise-1.05;const morningFull=sunrise+1.25;const afternoonBlendStart=Math.min(solarNoon+1.25,sunset-3.0);const afternoonFull=Math.min(solarNoon+3.0,sunset-1.55);const duskStart=Math.max(afternoonFull,sunset-1.35);const nightFull=sunset+1.05;if(h<dawnStart||h>=nightFull)return{phase:'night',palette:solarPalettes.night};if(h<morningFull){const t=(h-dawnStart)/(morningFull-dawnStart);return{phase:t<.5?'night':'morning',palette:mixPalette(solarPalettes.night,solarPalettes.morning,t)}}if(h<afternoonBlendStart)return{phase:'morning',palette:solarPalettes.morning};if(h<afternoonFull){const t=(h-afternoonBlendStart)/(afternoonFull-afternoonBlendStart);return{phase:t<.5?'morning':'afternoon',palette:mixPalette(solarPalettes.morning,solarPalettes.afternoon,t)}}if(h<duskStart)return{phase:'afternoon',palette:solarPalettes.afternoon};const t=(h-duskStart)/(nightFull-duskStart);return{phase:t<.58?'afternoon':'night',palette:mixPalette(solarPalettes.afternoon,solarPalettes.night,t)}}
function applyPalette(palette){const s=document.body.style;s.setProperty('--bg',palette.bg);s.setProperty('--surface',palette.surface);s.setProperty('--surface-2',palette.surface2);s.setProperty('--text',palette.text);s.setProperty('--muted',palette.muted);s.setProperty('--line',palette.line);s.setProperty('--accent',palette.accent);s.setProperty('--accent-2',palette.accent2);s.setProperty('--chip',palette.chip);s.setProperty('--nav',palette.nav)}
function clearPalette(){['--bg','--surface','--surface-2','--text','--muted','--line','--accent','--accent-2','--chip','--nav'].forEach(v=>document.body.style.removeProperty(v))}
function themeLanguage(){const l=(document.documentElement.lang||'es').toLowerCase().split('-')[0];return portfolioThemeLabels[l]?l:'es'}
function updateThemeButton(){const b=document.getElementById('themeButton');if(!b)return;const labels=portfolioThemeLabels[themeLanguage()];b.dataset.phase=portfolioThemeMode;b.textContent=labels[portfolioThemeMode]||labels.auto;b.setAttribute('aria-label',`${labels.auto}: ${b.textContent}`)}
function applySolarTheme(){document.body.setAttribute('data-visual-style',portfolioVisualStyle);if(portfolioThemeMode==='auto'){const state=automaticSolarState();applyPalette(state.palette);document.body.dataset.dayPhase=state.phase;document.body.dataset.theme=state.phase==='night'?'dark':state.phase==='afternoon'?'afternoon':'light';}else{clearPalette();const phase=portfolioThemeMode;document.body.dataset.dayPhase=phase;document.body.dataset.theme=phase==='night'?'dark':phase==='afternoon'?'afternoon':'light';}updateThemeButton()}
function installSolarTheme(){let saved='auto';try{saved=localStorage.getItem('portfolio-theme')||'auto'}catch(e){}if(saved==='light')saved='morning';if(saved==='dark')saved='night';if(!['auto','morning','afternoon','night'].includes(saved))saved='auto';portfolioThemeMode=saved;portfolioApplyTheme=applySolarTheme;const old=document.getElementById('themeButton');if(old){const b=old.cloneNode(true);old.replaceWith(b);b.addEventListener('click',event=>{if(event.altKey){event.preventDefault();portfolioToggleThemePanel();return}const modes=['auto','morning','afternoon','night'];portfolioThemeMode=modes[(modes.indexOf(portfolioThemeMode)+1)%modes.length];try{localStorage.setItem('portfolio-theme',portfolioThemeMode)}catch(e){}applySolarTheme()})}applySolarTheme();setInterval(()=>{if(portfolioThemeMode==='auto')applySolarTheme()},60000);document.addEventListener('portfolio-language-change',updateThemeButton);window.addEventListener('focus',()=>{if(portfolioThemeMode==='auto')applySolarTheme()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&portfolioThemeMode==='auto')applySolarTheme()})}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',installSolarTheme,{once:true});else installSolarTheme();
