const extraProjectDescriptions={
  es:{cosmocronia:'Biografía temporal e interactiva del universo, desde el Big Bang hasta la muerte térmica, con cono 3D, cronología semántica, atlas y enciclopedia científica documentada.',ide:'Entorno de desarrollo híbrido y multilenguaje para navegador y escritorio, con Monaco, proyectos reales, diagnósticos, ejecución web y Python, y compilación nativa mediante toolchains locales.'},
  ca:{cosmocronia:'Biografia temporal i interactiva de l’univers, des del Big Bang fins a la mort tèrmica, amb con 3D, cronologia semàntica, atles i enciclopèdia científica documentada.',ide:'Entorn de desenvolupament híbrid i multillenguatge per a navegador i escriptori, amb Monaco, projectes reals, diagnòstics, execució web i Python, i compilació nativa mitjançant toolchains locals.'},
  en:{cosmocronia:'An interactive temporal biography of the universe, from the Big Bang to heat death, with a 3D cone, semantic timeline, atlases and a documented scientific encyclopedia.',ide:'Hybrid multilanguage development environment for browser and desktop, with Monaco, real projects, diagnostics, web and Python execution, and native compilation through local toolchains.'},
  fr:{cosmocronia:'Biographie temporelle et interactive de l’univers, du Big Bang à la mort thermique, avec cône 3D, chronologie sémantique, atlas et encyclopédie scientifique documentée.',ide:'Environnement de développement hybride et multilangage pour navigateur et bureau, avec Monaco, projets réels, diagnostics, exécution web et Python, et compilation native via les chaînes d’outils locales.'},
  de:{cosmocronia:'Interaktive Zeitbiografie des Universums vom Big Bang bis zum Wärmetod, mit 3D-Kegel, semantischer Zeitleiste, Atlanten und dokumentierter wissenschaftlicher Enzyklopädie.',ide:'Hybride mehrsprachige Entwicklungsumgebung für Browser und Desktop mit Monaco, realen Projekten, Diagnosefunktionen, Web- und Python-Ausführung sowie nativer Kompilierung über lokale Toolchains.'},
  pt:{cosmocronia:'Biografia temporal e interativa do universo, do Big Bang à morte térmica, com cone 3D, cronologia semântica, atlas e enciclopédia científica documentada.',ide:'Ambiente de desenvolvimento híbrido e multilinguagem para navegador e desktop, com Monaco, projetos reais, diagnósticos, execução web e Python e compilação nativa através de toolchains locais.'},
  it:{cosmocronia:'Biografia temporale e interattiva dell’universo, dal Big Bang alla morte termica, con cono 3D, cronologia semantica, atlanti ed enciclopedia scientifica documentata.',ide:'Ambiente di sviluppo ibrido e multilinguaggio per browser e desktop, con Monaco, progetti reali, diagnostica, esecuzione web e Python e compilazione nativa tramite toolchain locali.'}
};
function applyExtraProjectDescriptions(lang){const data=extraProjectDescriptions[lang]||extraProjectDescriptions.es;Object.entries(data).forEach(([key,text])=>{const node=document.querySelector('.project-card>p[data-project-key="'+key+'"]');if(node)node.textContent=text})}
function initExtraProjectDescriptions(){const select=document.getElementById('languageSelect');const run=()=>setTimeout(()=>applyExtraProjectDescriptions(select?.value||document.documentElement.lang||'es'),0);run();if(select&&!select.dataset.extraProjectsBound){select.dataset.extraProjectsBound='true';select.addEventListener('change',run)}document.addEventListener('portfolio-language-change',event=>applyExtraProjectDescriptions(event.detail?.lang||select?.value||'es'))}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',initExtraProjectDescriptions,{once:true});else initExtraProjectDescriptions();